/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-Stock_Glance-qrdwkc9G7ngmdEqK3XHzNe-wWRTgqLN2",
  "version": "2020-11-20"
}

export default ebconfig;